base_images:
  base:
    name: "4.9"
    namespace: ocp
    tag: base
build_root: #
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
  - dockerfile_path: build/Dockerfile
    to: quay.io/konveyor/openshift-velero-plugin:latest
promotion:
  name: "4.9"
  namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.9"
  namespace: ocp
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: make test
      from: stable:oadp-operator-e2e
      resources:
        requests:
          cpu: 100m
    workflow: "ipi-aws"
zz_generated_metadata:
  branch: master
  org: openshift
  repo: openshift-velero-plugin
