base_images:
  base:
    name: "4.9"
    namespace: ocp
    tag: base
  os:
    name: centos
    namespace: openshift
    tag: "7"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
promotion:
  name: "4.9"
  namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.9"
  namespace: ocp
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    env:
      OO_CHANNEL: alpha
      OO_INSTALL_NAMESPACE: oadp-operator
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
    workflow: openshift-e2e-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: openshift-velero-plugin
