base_images:
  base:
    name: "4.9"
    namespace: ocp
    tag: base
build_root: # declares that the release:golang-1.13 image has the build-time dependencies
  image_stream_tag:
    name: "release"
    namespace: "openshift"
    tag: "golang-1.14"
images:
- dockerfile_path: Dockerfile
  to: quay.io/konveyor/openshift-velero-plugin:latest
releases:
  latest:
    release:
      channel: stable
      version: "4.7"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: plugin-e2e
  steps:
    cluster_profile: aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: alpha
      OO_INSTALL_NAMESPACE: oadp-operator
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
    test:
    - as: e2e
      commands: make test
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: optional-operators-ci-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: openshift-velero-plugin
